# Generated by Django 3.2.5 on 2021-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210715_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='on_off',
            field=models.BooleanField(default=False),
        ),
    ]
